homeassistant:
  packages: !include_dir_merge_named configuration/package

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

#comment testing git-pull addon in hassio

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

camera:
  - platform: generic
    still_image_url: "http://192.168.1.160/cgi-bin/snapshot.cgi"
    stream_source: "not_used_as_does_not_work_ERROR (stream_worker) [libav.rtsp] method OPTIONS failed: 401 Unauthorized"
    authentication: digest
    verify_ssl: false
    username: !secret camera_dahua_front_username
    password: !secret camera_dahua_front_password
  
#   - platform: generic
#     still_image_url: "http://192.168.1.161/cgi-bin/snapshot.cgi"
#     stream_source: "not_used_as_does_not_work_ERROR (stream_worker) [libav.rtsp] method OPTIONS failed: 401 Unauthorized"
#     authentication: digest
#     verify_ssl: false
#     username: !secret camera_dahua_second_username
#     password: !secret camera_dahua_second_password




#-----WARNING:----- 
# completely deactivate the sonoff component from HA while doing a firmware update, 
# due to auto-relogin function you might be kicked out of the app before the process is completed. 
# I would not be held liable for any problems occuring if not following this steps!

# https://github.com/peterbuga/HASS-sonoff-ewelink
# REMEMBER TO SHARE IT WITH ACCOUNT SET HERE TO MAKE IT VISIBLE FOR HA
sonoff:
 username: !secret sonoff_ewelink_username
 password: !secret sonoff_ewelink_password
 scan_interval: 60
 grace_period: 600
 api_region: 'eu'
 entity_prefix: True
 debug: False
  
climate:
  - platform: generic_thermostat
    name: Spa
    heater: switch.sonoff_10005bb9e1
    target_sensor: sensor.spa_temperature_with_offset
    min_temp: 20
    max_temp: 45
    target_temp: 36
    cold_tolerance: 1
    hot_tolerance: 1
    min_cycle_duration:
        minutes: 5
    initial_hvac_mode: "heat"
    precision: 1.0
    

automower:
  username: !secret husqvarna_username
  password: !secret husqvarna_password

device_tracker:
  - platform: google_maps
    username: !secret device_tracker_google_maps_username

rest_command:
  gate_open_close:
    url: !secret supla_direct_link_gate_open_close
    method: GET
    
binary_sensor:
  - platform: template
    sensors:
      gate:
        friendly_name: "Gate"
        device_class: garage_door
        value_template: "{{ is_state('sensor.gate_closed', 'False') }}"
          
cover:
  - platform: template
    covers:
      gateway:
        friendly_name: "Gateway"
        value_template: "{{ is_state('binary_sensor.gate', 'on') }}"
        device_class: garage
        open_cover:
          service: rest_command.gate_open_close
        close_cover:
          service: rest_command.gate_open_close
        stop_cover:
          service: rest_command.gate_open_close

input_boolean:
  nobody_home:
    name: Nikogo nie ma w domu
    initial: false
  everyone_asleep:
    name: Wszyscy spia
    initial: false
  max_clean:
    name: Max czyszczenie
    initial: false
  night_clean:
    name: Nocne czyszczenie
    initial: false

input_number:
  max_aqi_for_xiaomi:
    name: Max AQI for Xiaomi rooms
    initial: 15
    min: 1
    max: 60
    mode: box
  min_humidity:
    name: Min humidity
    initial: 48
    min: 1
    max: 100
    mode: box
  max_humidity:
    name: Max humidity
    initial: 52
    min: 1
    max: 100
    mode: box
  min_alert_spa_machinery_temperature:
    name: Min Alert Spa Machinery Temperature
    initial: 15
    min: 1
    max: 50
    mode: box
  asleep_ilumination_threshold:
    name: Asleep Ilumination Threshold
    initial: 15
    min: 1
    max: 1000
    mode: box

    
input_datetime:
  bathroom_lights_on_time:
    name: Bathroom Lights Shelves On Time
    has_date: false
    has_time: true

notify:
  - name: android_lukasz
    platform: simplepush
    device_key: !secret simplepush_lukasz_android_device_key

fan:
# Xiaomi Air Purifier Pro - Living Room
  - platform: xiaomi_miio
    name: Living Room Xiaomi
    host: 192.168.1.140
    token: !secret xiaomi_air_purifier_pro_token

# Xiaomi Air Purifier 2 Garage
  - platform: xiaomi_miio
    name: Garage Xiaomi
    host: 192.168.1.141
    token: !secret xiaomi_air_purifier_2_garage_token
    
# Xiaomi Air Purifier 2S Bedroom
  - platform: xiaomi_miio
    name: Bedroom Xiaomi
    host: 192.168.1.142
    token: !secret xiaomi_air_purifier_2s_bedroom_token
    
# Xiaomi Air Purifier 2S Kids Room
  - platform: xiaomi_miio
    name: Kids Room Xiaomi
    host: 192.168.1.143
    token: !secret xiaomi_air_purifier_2s_kidsroom_token
    
# Xiaomi Air Purifier 2S Playroom
  - platform: xiaomi_miio
    name: Playroom Xiaomi
    host: 192.168.1.164
    token: !secret xiaomi_air_purifier_2s_playroom_token
    
# HUMIDIFIERS
# Xiaomi Humidifier (real model is: zhimi.humidifier.cb1)
  - platform: xiaomi_miio
    name: Living Room Humidifier
    host: 192.168.1.165
    token: !secret xiaomi_humidifier_token
    
wemo:
  discovery: false
  static:
    - 192.168.1.145
    
# You can leave MAC empty if you only have one gateway.
xiaomi_aqara:
  discovery_retry: 5
  gateways:
    # - host: 192.168.1.151
    #   key: !secret xiaomi_aquara_key
    
    # - mac: !secret xiaomi_aquara_mac
    #   key: !secret xiaomi_aquara_key
      
     - host: 192.168.1.151
       mac: !secret xiaomi_aquara_mac
       key: !secret xiaomi_aquara_key
    
ifttt:
  key: !secret ifttt_key
  
tado:
  username: !secret tado_account_username
  password: !secret tado_account_password


# Sensors
sensor:
  - platform: time_date
    display_options:
      - 'time'

    # can I get ride of that and have only binary_sensor ? Was unable to template binary sensor value properly...
  - platform: rest
    resource: !secret supla_direct_link_gate_read
    method: GET
    name: Gate Closed
    value_template: "{{ value_json.hi }}"

  - platform: template
    sensors:
        #4 oczyszczacze powietrza Xiaomi
        xiaomi_pro_aqi:
            friendly_name: "Living Room Xiaomi AQI"
            value_template: '{{ states.fan.livingroom_xiaomi.attributes.aqi|default(0) }}'
            unit_of_measurement: "AQI"
        xiaomi_pro_temperature:
            friendly_name: "Living Room Xiaomi temperature"
            value_template: '{{ states.fan.livingroom_xiaomi.attributes.temperature|default(0) }}'
            unit_of_measurement: "℃"
            icon_template: mdi:thermometer
        xiaomi_pro_humidity:
            friendly_name: "Living Room Xiaomi humidity"
            value_template: '{{ states.fan.livingroom_xiaomi.attributes.humidity|default(0) }}'
            unit_of_measurement: "%"
        xiaomi_pro_mode:
            friendly_name: "Living Room Xiaomi mode"
            value_template: '{{ states.fan.livingroom_xiaomi.attributes.mode }}'
        
        xiaomi_garage_aqi:
            friendly_name: "Garage Xiaomi AQI"
            value_template: '{{ states.fan.garage_xiaomi.attributes.aqi|default(0) }}'
            unit_of_measurement: "AQI"
        xiaomi_garage_temperature:
            friendly_name: "Garage Xiaomi temperature"
            value_template: '{{ states.fan.garage_xiaomi.attributes.temperature|default(0) }}'
            unit_of_measurement: "℃"
            icon_template: mdi:thermometer
        xiaomi_garage_humidity:
            friendly_name: "Garage Xiaomi humidity"
            value_template: '{{ states.fan.garage_xiaomi.attributes.humidity|default(0) }}'
            unit_of_measurement: "%"
        xiaomi_garage_mode:
            friendly_name: "Garage Xiaomi mode"
            value_template: '{{ states.fan.garage_xiaomi.attributes.mode }}'
            
        xiaomi_bedroom_aqi:
            friendly_name: "Bedroom Xiaomi AQI"
            value_template: '{{ states.fan.bedroom_xiaomi.attributes.aqi|default(0) }}'
            unit_of_measurement: "AQI"
        xiaomi_bedroom_temperature:
            friendly_name: "Bedroom Xiaomi temperature"
            value_template: '{{ states.fan.bedroom_xiaomi.attributes.temperature|default(0) }}'
            unit_of_measurement: "℃"
            icon_template: mdi:thermometer
        xiaomi_bedroom_humidity:
            friendly_name: "Bedroom Xiaomi humidity"
            value_template: '{{ states.fan.bedroom_xiaomi.attributes.humidity|default(0) }}'
            unit_of_measurement: "%"
        xiaomi_bedroom_mode:
            friendly_name: "Bedroom Xiaomi mode"
            value_template: '{{ states.fan.bedroom_xiaomi.attributes.mode }}'
            
        xiaomi_kidsroom_aqi:
            friendly_name: "Kids Room Xiaomi AQI"
            value_template: '{{ states.fan.kidsroom_xiaomi.attributes.aqi|default(0) }}'
            unit_of_measurement: "AQI"
        xiaomi_kidsroom_temperature:
            friendly_name: "Kids Room Xiaomi temperature"
            value_template: '{{ states.fan.kidsroom_xiaomi.attributes.temperature|default(0) }}'
            unit_of_measurement: "℃"
            icon_template: mdi:thermometer
        xiaomi_kidsroom_humidity:
            friendly_name: "Kids Room Xiaomi humidity"
            value_template: '{{ states.fan.kidsroom_xiaomi.attributes.humidity|default(0) }}'
            unit_of_measurement: "%"
        xiaomi_kidsroom_mode:
            friendly_name: "Kids Room Xiaomi mode"
            value_template: '{{ states.fan.kidsroom_xiaomi.attributes.mode }}'
            
        xiaomi_playroom_aqi:
            friendly_name: "Playroom Xiaomi AQI"
            value_template: '{{ states.fan.playroom_xiaomi.attributes.aqi|default(0) }}'
            unit_of_measurement: "AQI"
        xiaomi_playroom_temperature:
            friendly_name: "Playroom Xiaomi temperature"
            value_template: '{{ states.fan.playroom_xiaomi.attributes.temperature|default(0) }}'
            unit_of_measurement: "℃"
            icon_template: mdi:thermometer
        xiaomi_playroom_humidity:
            friendly_name: "Playroom Xiaomi humidity"
            value_template: '{{ states.fan.playroom_xiaomi.attributes.humidity|default(0) }}'
            unit_of_measurement: "%"
        xiaomi_playroom_mode:
            friendly_name: "Playroom Xiaomi mode"
            value_template: '{{ states.fan.playroom_xiaomi.attributes.mode }}'
            
        xiaomi_living_room_humidifier_mode:
            friendly_name: "Living Room Xiaomi Humidifier mode"
            value_template: '{{ states.fan.living_room_humidifier.attributes.mode }}'
            
        spa_temperature_with_offset:
            friendly_name: "SPA Temperature"
            value_template: '{{ states.sensor.sonoff_10005bb9e1_temperature.state | int + 2}}'
            
        living_room_humidifier_water_level:
            friendly_name: "Humidifier Water Level"
            value_template: '{{ ((states.fan.living_room_humidifier.attributes.depth | int / 130) * 100) | round(0) }}'
            unit_of_measurement: "%"
    
  - platform: rest
    resource: !secret looko2_api_url_with_token
    name: "PM1"
    unit_of_measurement: 'ug/m3'
    value_template: '{{value_json.PM1}}'
            
  - platform: rest
    resource: !secret looko2_api_url_with_token
    name: "PM2.5"
    unit_of_measurement: 'ug/m3'
    value_template: '{{value_json.PM25}}'
    
  - platform: rest
    resource: !secret looko2_api_url_with_token
    name: "PM10"
    unit_of_measurement: 'ug/m3'
    value_template: '{{value_json.PM10}}'
    
  - platform: xiaomi_miio
    name: Xiaomi Air Monitor Living Room
    host: 192.168.1.144
    token: !secret xiaomi_miio_air_monitor_Living_room_token
