homeassistant:
  packages: !include_dir_merge_named configuration/package

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

#comment testing git-pull addon in hassio

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

camera:
  - platform: generic
    still_image_url: "http://192.168.1.160/cgi-bin/snapshot.cgi"
    stream_source: "not_used_as_does_not_work_ERROR (stream_worker) [libav.rtsp] method OPTIONS failed: 401 Unauthorized"
    authentication: digest
    verify_ssl: false
    username: !secret camera_dahua_front_username
    password: !secret camera_dahua_front_password
  
  - platform: generic
    still_image_url: "http://192.168.1.161/cgi-bin/snapshot.cgi"
    stream_source: "not_used_as_does_not_work_ERROR (stream_worker) [libav.rtsp] method OPTIONS failed: 401 Unauthorized"
    authentication: digest
    verify_ssl: false
    username: !secret camera_dahua_second_username
    password: !secret camera_dahua_second_password
#-----WARNING:----- 
# completely deactivate the sonoff component from HA while doing a firmware update, 
# due to auto-relogin function you might be kicked out of the app before the process is completed. 
# I would not be held liable for any problems occuring if not following this steps!

# https://github.com/peterbuga/HASS-sonoff-ewelink
sonoff:
 username: !secret sonoff_ewelink_username
 password: !secret sonoff_ewelink_password
 scan_interval: 60
 grace_period: 600
 api_region: 'eu'
 entity_prefix: True
 debug: False
  
climate:
  - platform: generic_thermostat
    name: Spa
    heater: switch.sonoff_10005bb9e1
    target_sensor: sensor.sonoff_10005bb9e1_temperature
    min_temp: 20
    max_temp: 45
    target_temp: 33
    cold_tolerance: 1
    hot_tolerance: 1
    min_cycle_duration:
        minutes: 5
    initial_hvac_mode: "heat"
    precision: 1.0
    

automower:
  username: !secret husqvarna_username
  password: !secret husqvarna_password

device_tracker:
  - platform: google_maps
    username: !secret device_tracker_google_maps_username

rest_command:
  gate_open_close:
    url: !secret supla_direct_link_gate_open_close
    method: GET
    
binary_sensor:
  - platform: template
    sensors:
      gate:
        friendly_name: "Gate"
        device_class: garage_door
        value_template: "{{ is_state('sensor.gate_closed', 'False') }}"
          
cover:
  - platform: template
    covers:
      gateway:
        friendly_name: "Gateway"
        value_template: "{{ is_state('binary_sensor.gate', 'on') }}"
        device_class: garage
        open_cover:
          service: rest_command.gate_open_close
        close_cover:
          service: rest_command.gate_open_close
        stop_cover:
          service: rest_command.gate_open_close

input_boolean:
  nobody_home:
    name: Nikogo nie ma w domu
    initial: false
  max_clean:
    name: Max czyszczenie wlaczone
    initial: false

input_number:
  max_aqi_for_xiaomi:
    name: Max AQI for Xiaomi rooms
    initial: 20
    min: 1
    max: 60
    mode: box
  max_aqi_for_livnig_room:
    name: Max AQI for Living Room
    initial: 20
    min: 1
    max: 60
    mode: box
  min_humidity:
    name: Min humidity
    initial: 45
    min: 1
    max: 100
    mode: box
  max_humidity:
    name: Max humidity
    initial: 55
    min: 1
    max: 100
    mode: box
  min_alert_spa_machinery_temperature:
    name: Min Alert Spa Machinery Temperature
    initial: 15
    min: 1
    max: 50
    mode: box

notify:
  - name: android_lukasz
    platform: simplepush
    device_key: !secret simplepush_lukasz_android_device_key

fan:
# Xiaomi Air Purifier Pro
  - platform: xiaomi_miio
    name: Playroom Xiaomi
    host: 192.168.1.140
    token: !secret xiaomi_air_purifier_pro_token

# Xiaomi Air Purifier 2 Garage
  - platform: xiaomi_miio
    name: Garage Xiaomi
    host: 192.168.1.141
    token: !secret xiaomi_air_purifier_2_garage_token
    
# Xiaomi Air Purifier 2S Bedroom
  - platform: xiaomi_miio
    name: Bedroom Xiaomi
    host: 192.168.1.142
    token: !secret xiaomi_air_purifier_2s_bedroom_token
    
# Xiaomi Air Purifier 2S Kids Room
  - platform: xiaomi_miio
    name: Kids Room Xiaomi
    host: 192.168.1.143
    token: !secret xiaomi_air_purifier_2s_kidsroom_token
    
wemo:
  discovery: false
  static:
    - 192.168.1.145
    
# You can leave MAC empty if you only have one gateway.
xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - key: !secret xiaomi_aquara_key
    
ifttt:
  key: !secret ifttt_key
  
tado:
  username: !secret tado_account_username
  password: !secret tado_account_password


# Sensors
sensor:
    # can I get ride of that and have only binary_sensor ? Was unable to template binary sensor value properly...
  - platform: rest
    resource: !secret supla_direct_link_gate_read
    method: GET
    name: Gate Closed
    value_template: "{{ value_json.hi }}"

  - platform: template
    sensors:
        #4 oczyszczacze powietrza Xiaomi
        xiaomi_pro_aqi:
            friendly_name: "Playroom AQI"
            value_template: '{{ states.fan.playroom_xiaomi.attributes.aqi|default(0) }}'
            unit_of_measurement: "AQI"
        xiaomi_pro_temperature:
            friendly_name: "Playroom temperature"
            value_template: '{{ states.fan.playroom_xiaomi.attributes.temperature|default(0) }}'
            unit_of_measurement: "℃"
            icon_template: mdi:thermometer
        xiaomi_pro_humidity:
            friendly_name: "Playroom humidity"
            value_template: '{{ states.fan.playroom_xiaomi.attributes.humidity|default(0) }}'
            unit_of_measurement: "%"
        
        xiaomi_garage_aqi:
            friendly_name: "Garage AQI"
            value_template: '{{ states.fan.garage_xiaomi.attributes.aqi|default(0) }}'
            unit_of_measurement: "AQI"
        xiaomi_garage_temperature:
            friendly_name: "Garage temperature"
            value_template: '{{ states.fan.garage_xiaomi.attributes.temperature|default(0) }}'
            unit_of_measurement: "℃"
            icon_template: mdi:thermometer
        xiaomi_garage_humidity:
            friendly_name: "Garage humidity"
            value_template: '{{ states.fan.garage_xiaomi.attributes.humidity|default(0) }}'
            unit_of_measurement: "%"
            
        xiaomi_bedroom_aqi:
            friendly_name: "Bedroom AQI"
            value_template: '{{ states.fan.bedroom_xiaomi.attributes.aqi|default(0) }}'
            unit_of_measurement: "AQI"
        xiaomi_bedroom_temperature:
            friendly_name: "Bedroom temperature"
            value_template: '{{ states.fan.bedroom_xiaomi.attributes.temperature|default(0) }}'
            unit_of_measurement: "℃"
            icon_template: mdi:thermometer
        xiaomi_bedroom_humidity:
            friendly_name: "Bedroom humidity"
            value_template: '{{ states.fan.bedroom_xiaomi.attributes.humidity|default(0) }}'
            unit_of_measurement: "%"
            
        xiaomi_kidsroom_aqi:
            friendly_name: "Kids Room AQI"
            value_template: '{{ states.fan.kidsroom_xiaomi.attributes.aqi|default(0) }}'
            unit_of_measurement: "AQI"
        xiaomi_kidsroom_temperature:
            friendly_name: "Kids Room temperature"
            value_template: '{{ states.fan.kidsroom_xiaomi.attributes.temperature|default(0) }}'
            unit_of_measurement: "℃"
            icon_template: mdi:thermometer
        xiaomi_kidsroom_humidity:
            friendly_name: "Kids Room humidity"
            value_template: '{{ states.fan.kidsroom_xiaomi.attributes.humidity|default(0) }}'
            unit_of_measurement: "%"
    
  - platform: rest
    resource: !secret looko2_api_url_with_token
    name: "PM1"
    unit_of_measurement: 'ug/m3'
    value_template: '{{value_json.PM1}}'
            
  - platform: rest
    resource: !secret looko2_api_url_with_token
    name: "PM2.5"
    unit_of_measurement: 'ug/m3'
    value_template: '{{value_json.PM25}}'
    
  - platform: rest
    resource: !secret looko2_api_url_with_token
    name: "PM10"
    unit_of_measurement: 'ug/m3'
    value_template: '{{value_json.PM10}}'
    
  - platform: xiaomi_miio
    name: Xiaomi Air Monitor Living Room
    host: 192.168.1.144
    token: !secret xiaomi_miio_air_monitor_Living_room_token
